### ISSUE TITLE
Plugin problem with new directadmin evolution skin

### ISSUE THREAD

**Issue by tuthost** [SpamExperts/directadmin-addon#17]
### Version information

4.0.1508925016

We are testing on our server new Directadmin skin - evolution, that is in beta now, but will be released very soon. This is new default directadmin skin.

And there is some problem with your plugin in new skin.
When we try use check status link at any users
https://mail1.tuthost.com:2222/CMD_PLUGINS/spamexperts

we got error in console:
VM767:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Function.parseJSON (spamexperts?iframe=yes:5)
at parseAjaxResponse (spamexperts?iframe=yes:13)
at Object.success (spamexperts?iframe=yes:178)
at c (spamexperts?iframe=yes:5)
at Object.fireWith [as resolveWith] (spamexperts?iframe=yes:5)
at k (spamexperts?iframe=yes:7)
at XMLHttpRequest.r (spamexperts?iframe=yes:7)

And check button does not work. Maybe you could check your plugin work with new directadmin skin?

**Comment by for93t** [comment]
The issue has been fixed [here](https://github.com/SpamExperts/directadmin-addon/commit/0cb8bbecc525a049feea81bebd65015255f3a24d). I did not notice that it was converted into an enhancement :(

**Comment by tuthost** [comment]
We just update plugin from this repository, but it does not help.
The problem still exist on admin, reseller and user level.

**Comment by for93t** [comment]
@tuthost, can you please open the Developer tools in your browser (usually by pressing the F12 key), try to reproduce the problem and records the request that the plugin executes (in the Network tab)? Does the query string have the `&iframe=yes` tail?

**Comment by tuthost** [comment]
Hello.
When i press check status in evolution skin on user level i got error 
`VM128:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (spamexperts?iframe=yes:5)
    at parseAjaxResponse (spamexperts?iframe=yes:13)
    at Object.success (spamexperts?iframe=yes:178)
    at c (spamexperts?iframe=yes:5)
    at Object.fireWith [as resolveWith] (spamexperts?iframe=yes:5)
    at k (spamexperts?iframe=yes:7)
    at XMLHttpRequest.r (spamexperts?iframe=yes:7)`

on admin level

`Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (spamexperts?iframe=yes:5)
    at parseAjaxResponse (spamexperts?iframe=yes:13)
    at Object.success (spamexperts?iframe=yes:786)
    at c (spamexperts?iframe=yes:5)
    at Object.fireWith [as resolveWith] (spamexperts?iframe=yes:5)
    at k (spamexperts?iframe=yes:7)
    at XMLHttpRequest.r (spamexperts?iframe=yes:7)`

**Comment by for93t** [comment]
@tuthost I was asking about the query string, not the error, like here:
![image](https://user-images.githubusercontent.com/2736458/44144095-e0f3f3d2-a08e-11e8-85a5-3433cc590156.png)

**Comment by tuthost** [comment]
Hello.

Thanks for example. Now query string does not contain &iframe=yes 
Please check screenshot
https://www.dropbox.com/s/zxwo0uj6nkmfj9f/spamexperts.PNG?dl=0

**Comment by for93t** [comment]
Thanks for the additional info, @tuthost. That could mean that you are still running the old code because your add-on instance was not updated properly. I'd suggest you to wait for the next official release and update your system once it's available. Thanks for the assistance!

**Comment by tuthost** [comment]
How can we update it now, manually? Because in directadmin plugin manager it does not show current version and Available Version?

**Comment by for93t** [comment]
To update the package manually you have to change the production scripts to apply the changes form the [fix](https://github.com/SpamExperts/directadmin-addon/commit/0cb8bbecc525a049feea81bebd65015255f3a24d).

A newer version of the add-on package (with the fix included) is not released yet. That's why your add-on does not indicate any possibility to upgrade. Unfortunately, at the moment I cannot provide you with any ETA of the next release.

**Comment by Keuvie** [comment]
Hi SpamExperts,

Please provide more info regarding the new release.

**Comment by LaurentiuTeodorescu** [comment]
This was fixed in https://github.com/SpamExperts/directadmin-addon/pull/21
Should work fine with latest version of Add-on:  **4.0.1620903275** (released)
